version: "3"

services:
  namenode:
    image: hadoop-namenode:latest
    container_name: namenode
    ports:
      - "9870:9870" # NameNode UI
      - "9000:9000" # NameNode RPC
    volumes:
      - ./hadoop/namenode/data:/hadoop/dfs/name
    environment:
      - HDFS_NAMENODE_USER=hdfs
      - HDFS_DATANODE_USER=hdfs
      - HDFS_SECONDARYNAMENODE_USER=hdfs
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_USER=root
      - HADOOP_SSH_OPTS="-o StrictHostKeyChecking=no"
    env_file:
      - ./hadoop.env
    networks:
      - bdt-network

  datanode:
    image: hadoop-datanode:latest
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864" # DataNode UI
    volumes:
      - ./hadoop/datanode/data:/hadoop/dfs/data
    environment:
      - HDFS_NAMENODE_USER=hdfs
      - HDFS_DATANODE_USER=hdfs
      - HDFS_SECONDARYNAMENODE_USER=hdfs
    env_file:
      - ./hadoop.env
    networks:
      - bdt-network

  jupyter-notebook:
    container_name: jupyter-notebook
    image: jupyter-notebooks:latest
    volumes:
      - "./scripts/sparkdata:/sparkdata"
      - "./scripts/work:/home/jovyan/work"
    ports:
      - "8888:8888"
    networks:
      - bdt-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    volumes:
      - ./postgres/init-hive-metastore.sql:/docker-entrypoint-initdb.d/init-hive-metastore.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - bdt-network

  hive-metastore:
    image: hive-metastore:latest
    container_name: hive-metastore
    environment:
      - HDFS_NAMENODE_USER=hdfs
      - HDFS_DATANODE_USER=hdfs
      - HDFS_SECONDARYNAMENODE_USER=hdfs
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hiveuser
      - POSTGRES_PASSWORD=hivepassword
      - HIVE_CONF_DIR=/opt/hive/conf
    depends_on:
      - postgres
      - namenode
      - datanode
    ports:
      - "9083:9083"   # ACTUAL Thrift port
      - "10000:10000" # HiveServer2
      - "10002:10002" # Hive Metastore Thrift
    networks:
      - bdt-network

volumes:
  hadoop_namenode:
  hadoop_datanode:
  postgres_data:

networks:
  bdt-network:
    driver: bridge
